/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Credit = {
  _type: "credit";
  role: "Photos" | "Video" | "Location";
  name: string;
  instagram?: string;
};

export type Video = {
  _type: "video";
  title: string;
  url?: string;
};

export type Media = {
  _type: "media";
  kind?: "image" | "youtube";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  youtubeUrl?: string;
  title?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  instagram: string;
  genres?: Array<string>;
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  texts?: {
    ticketsSoon?: string;
    followCta?: string;
    emptyTitle?: string;
    emptyText?: string;
    nightLabel?: string;
    notFoundText?: string;
    eventsDescription?: string;
    artistsDescription?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: Array<string>;
  cities?: string;
  soundsText?: Array<string>;
  genreCloud?: Array<{
    name: string;
    size: "s" | "m" | "l" | "xl";
    _type: "cloudGenre";
    _key: string;
  }>;
  formats?: Array<{
    label: string;
    text?: Array<string>;
    media?: Media;
    _type: "format";
    _key: string;
  }>;
  networkText?: Array<string>;
  networkMedia?: Media;
  seoDescription?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroMedia?: Media;
  tagline?: Array<string>;
  cities?: string;
  whatIs?: Array<string>;
  seoDescription?: string;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  showPage?: boolean;
  slug: Slug;
  instagram?: string;
  basedIn?: string;
  genres?: Array<string>;
  description?: string;
  portrait?: Media;
  work?: Array<
    {
      _key: string;
    } & Media
  >;
  credits?: Array<
    {
      _key: string;
    } & Credit
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ArtistReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artist";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  number: string;
  status: "upcoming" | "past";
  city: "Paris" | "Tokyo" | "Beijing";
  date?: string;
  venue?: string;
  ticketUrl?: string;
  text?: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroMedia?: Media;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  videos?: Array<
    {
      _key: string;
    } & Video
  >;
  lineup?: Array<
    {
      _key: string;
    } & ArtistReference
  >;
  credits?: Array<
    {
      _key: string;
    } & Credit
  >;
  seo?: Seo;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | Credit
  | Video
  | Media
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | AboutPage
  | HomePage
  | Artist
  | Slug
  | ArtistReference
  | Event
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && defined(slug.current)] | order(date desc, number desc) {    "slug": slug.current, number, title, city, date, venue, status, ticketUrl, text,    cover { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },    heroMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },    gallery[] { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },    videos[]{ _key, title, url },    "lineup": lineup[]-> { name, "slug": slug.current, instagram, "showPage": showPage == true },    credits[]{ _key, role, name, instagram }  }
export type EVENTS_QUERY_RESULT = Array<{
  slug: string;
  number: string;
  title: string;
  city: "Beijing" | "Paris" | "Tokyo";
  date: string | null;
  venue: string | null;
  status: "past" | "upcoming";
  ticketUrl: string | null;
  text: string | null;
  cover: {
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  };
  heroMedia: {
    kind: "image" | "youtube" | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    youtubeUrl: string | null;
    title: string | null;
    poster: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  }> | null;
  videos: Array<{
    _key: string;
    title: string;
    url: string | null;
  }> | null;
  lineup: Array<{
    name: string;
    slug: string;
    instagram: string | null;
    showPage: boolean | false;
  }> | null;
  credits: Array<{
    _key: string;
    role: "Location" | "Photos" | "Video";
    name: string;
    instagram: string | null;
  }> | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: ARTISTS_QUERY
// Query: *[_type == "artist" && defined(slug.current)] | order(lower(name) asc) {    name, "slug": slug.current, instagram, "showPage": showPage == true,    basedIn, genres, description,    portrait { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },    work[] { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },    credits[]{ _key, role, name, instagram }  }
export type ARTISTS_QUERY_RESULT = Array<{
  name: string;
  slug: string;
  instagram: string | null;
  showPage: boolean | false;
  basedIn: string | null;
  genres: Array<string> | null;
  description: string | null;
  portrait: {
    kind: "image" | "youtube" | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    youtubeUrl: string | null;
    title: string | null;
    poster: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: null;
    } | null;
  } | null;
  work: Array<{
    kind: "image" | "youtube" | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    youtubeUrl: string | null;
    title: string | null;
    poster: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: null;
    } | null;
  }> | null;
  credits: Array<{
    _key: string;
    role: "Location" | "Photos" | "Video";
    name: string;
    instagram: string | null;
  }> | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{ email, instagram, genres, texts }
export type SETTINGS_QUERY_RESULT = {
  email: string;
  instagram: string;
  genres: Array<string> | null;
  texts: {
    ticketsSoon?: string;
    followCta?: string;
    emptyTitle?: string;
    emptyText?: string;
    nightLabel?: string;
    notFoundText?: string;
    eventsDescription?: string;
    artistsDescription?: string;
  } | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{ heroMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }, tagline, cities, whatIs, seoDescription }
export type HOME_QUERY_RESULT = {
  heroMedia: {
    kind: "image" | "youtube" | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    youtubeUrl: string | null;
    title: string | null;
    poster: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: null;
    } | null;
  } | null;
  tagline: Array<string> | null;
  cities: string | null;
  whatIs: Array<string> | null;
  seoDescription: string | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    intro, cities, soundsText,    genreCloud[]{ name, size },    formats[]{ label, text, media { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } } },    networkText,    networkMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },    seoDescription  }
export type ABOUT_QUERY_RESULT = {
  intro: Array<string> | null;
  cities: string | null;
  soundsText: Array<string> | null;
  genreCloud: Array<{
    name: string;
    size: "l" | "m" | "s" | "xl";
  }> | null;
  formats: Array<{
    label: string;
    text: Array<string> | null;
    media: {
      kind: "image" | "youtube" | null;
      image: {
        asset: {
          _id: string;
          metadata: {
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string;
      } | null;
      youtubeUrl: string | null;
      title: string | null;
      poster: {
        asset: {
          _id: string;
          metadata: {
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: null;
      } | null;
    } | null;
  }> | null;
  networkText: Array<string> | null;
  networkMedia: {
    kind: "image" | "youtube" | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    } | null;
    youtubeUrl: string | null;
    title: string | null;
    poster: {
      asset: {
        _id: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: null;
    } | null;
  } | null;
  seoDescription: string | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "event" && defined(slug.current)] | order(date desc, number desc) {\n    "slug": slug.current, number, title, city, date, venue, status, ticketUrl, text,\n    cover { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },\n    heroMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n    gallery[] { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt },\n    videos[]{ _key, title, url },\n    "lineup": lineup[]-> { name, "slug": slug.current, instagram, "showPage": showPage == true },\n    credits[]{ _key, role, name, instagram }\n  }\n': EVENTS_QUERY_RESULT;
    '\n  *[_type == "artist" && defined(slug.current)] | order(lower(name) asc) {\n    name, "slug": slug.current, instagram, "showPage": showPage == true,\n    basedIn, genres, description,\n    portrait { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n    work[] { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n    credits[]{ _key, role, name, instagram }\n  }\n': ARTISTS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{ email, instagram, genres, texts }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{ heroMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } }, tagline, cities, whatIs, seoDescription }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    intro, cities, soundsText,\n    genreCloud[]{ name, size },\n    formats[]{ label, text, media { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } } },\n    networkText,\n    networkMedia { kind, image { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt }, youtubeUrl, title, poster { asset->{ _id, metadata { dimensions { width, height } } }, crop, hotspot, alt } },\n    seoDescription\n  }\n': ABOUT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
